compute_environment: LOCAL_MACHINE
distributed_type: NO
downcast_bf16: 'no'
enable_cpu_affinity: true
gpu_ids: '3'  # 仅使用 GPU 3
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1  # 单进程
rdzv_backend: static
same_network: true
use_cpu: false
main_process_port: 29503