compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
# dynamo_config:
#   dynamo_backend: INDUCTOR
#   dynamo_mode: default
#   dynamo_use_dynamic: true
#   dynamo_use_fullgraph: false
enable_cpu_affinity: true
gpu_ids: '2,1'
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
# mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
main_process_port: 29511